language: bash
services: docker
env:
  - PRODUCT=columnstore VERSION=1.2

install:
  - git clone https://github.com/mariadb-corporation/mariadb-docker-images.git ~/mariadb-docker-images

before_script:
  - env | sort
  - cd "$PRODUCT"
  - image="mariadb/$PRODUCT:$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ~/mariadb-docker-images/test/run.sh "$image"
  - docker rmi $(docker images --filter=reference='librarytest/*' -q) || true
  - echo 'y' | docker volume prune
  - bash ./test/test.sh "$image"
after_script:
- docker images

